var config = {
  PALM_KEY: "AIzaSyCjG5xgGj166rEzwgLW9Vm8ssLAJBe2Rmg",
  PEXELS_KEY: "WMNynpV8PSJVZhHrDiErkhOjr0bBPS0EBVCLBEpO7aGuBJHsntnVSjKX",
  FIREBASE_KEY: "AIzaSyAUwWsSSTBEWyIR9lqDFeZFdQKRjbJJOcI",
};
